const ALLOWED_IMAGE_TYPES = [
  "image/jpeg",
  "image/png",
  "image/webp",
  "image/gif",
  "image/svg+xml",
  "image/bmp",
  "image/tiff",
  "image/avif",
  "image/jxl",
  "image/webm",
  "image/ico",
  "image/cur",
  "image/pcx",
  "image/psd",
  "image/sgi",
  "image/tga",
  "image/vnd.microsoft.icon",
  "image/vnd.rn-realpix",
];
const ALLOWED_FILE_TYPES = [
  // PDF & Archive
  "application/pdf",
  "application/zip",
  "application/x-rar-compressed",
  "application/x-7z-compressed",
  // Video
  "video/mp4",
  "video/webm",
  "video/quicktime",
  // Audio
  "audio/mpeg",
  "audio/wav",
  "audio/ogg",
  "audio/webm",
  // Code & Text (MIME)
  "text/plain",
  "text/markdown",
  "text/html",
  "text/css",
  "text/javascript",
  "text/csv",
  "text/xml",
  "text/yaml",
  "text/x-python",
  "text/x-java-source",
  "text/x-go",
  "text/x-ruby",
  "text/x-php",
  "text/x-rustsrc",
  "text/x-swift",
  "text/x-kotlin",
  "text/x-csharp",
  "text/x-c++src",
  "text/x-csrc",
  "text/x-sh",
  "text/x-powershell",
  "text/x-scss",
  "text/x-less",
  "text/x-r",
  "text/x-rmd",
  "text/x-rmarkdown",
  "text/x-dart",
  "text/x-perl",
  "text/x-lua",
  "text/x-haskell",
  "text/x-elixir",
  "application/octet-stream",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "application/vnd.oasis.opendocument.text",
  // Data
  "application/json",
  "application/xml",
  "application/sql",
  "application/toml",
];

const MAX_FILE_SIZE = 200 * 1024 * 1024; // 200MB
const MAX_IMAGE_SIZE = 12 * 1024 * 1024; // 12MB

export {
  ALLOWED_IMAGE_TYPES,
  ALLOWED_FILE_TYPES,
  MAX_FILE_SIZE,
  MAX_IMAGE_SIZE,
};
